### ISSUE TITLE
Fix the absolute footer and make it relative to the meme image 

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/VS-Meme-Reddit#1]
When the meme image is long enough to reach the footer, it makes it overlapping with the footer, to avoid this change the CSS property of the footer from absolute to relative, or stick it to the bottom.

**Comment by devpnryn** [comment]
Hi @version0chiro,I would like to work on this issue.

**Comment by version0chiro** [comment]
Yup go ahead @devpnryn ! I will assign this issue to you.

**Comment by devpnryn** [comment]
I've raised a PR that contains fix to footer issue. Let me know if that fix is sufficient or not.
