### ISSUE TITLE
Error: Sluggish loading of new memes

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/VS-Meme-Reddit#4]
## Error: 
Sometimes the memes show a sluggish behavior before appearing on the extension after the press of the button.

## How to reproduce:
Just change the memes in a quick succession and you will observe a certain delay. This can restrict fluent transition between memes.

**Comment by devpnryn** [comment]
Hi @version0chiro,  I would like to work on this issue.

**Comment by version0chiro** [comment]
@devpnryn I have assigned this issue to you!

**Comment by devpnryn** [comment]
Raised a PR. check once and let me know if that resolves the mentioned issue.

**Comment by version0chiro** [comment]
Great Job @devpnryn !
