### ISSUE TITLE
Feature Request: Add a way to go back to previous Meme

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/VS-Meme-Reddit#5]
## Feature:
Sometimes people would like to revisit an old meme that they flew by in a hurry. To avoid this, we can add a temporary storage which will allow us to revisit the old memes as well as go ahead.

## Tips:
This can be easily achieved with help of caching or using any kind of dynamic data structure to hold onto some amount of previous memes you can come across.

**Comment by devpnryn** [comment]
Hey can I take up this?

**Comment by version0chiro** [comment]
Yup you surely can work on this @devpnryn
