### ISSUE TITLE
Update the readme screenshots and update the documentation 

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/VS-Meme-Reddit#7]
## The issue:
The screenshot  present in the readme file is out dated  since the last few updates. Run the extension on your local env, and update the screen shots.

Also feel free to make the readme more descriptive and informative.

**Comment by sanyamjain036** [comment]
<img width="1280" alt="Screenshot 2021-05-26 at 10 18 58 AM" src="https://user-images.githubusercontent.com/75247883/119604049-07856600-be0c-11eb-8488-36efbe14bab1.png">

check , if is this fine?

**Comment by version0chiro** [comment]
Yes this looks appropriate and clear! You can go ahead and add this to the readme.

**Comment by rhanmiano** [comment]
Would also like to volunteer to update README to update the screenshot, and update some typos. @version0chiro 😃

**Comment by version0chiro** [comment]
Go ahead @rhanmiano !
