### ISSUE TITLE
Add more available Reddit data to the shown meme

### ISSUE THREAD

**Issue by rhanmiano** [version0chiro/VS-Meme-Reddit#9]
## Summary
Hello @version0chiro , I'm pretty new to open source and would like to contribute to this project. Would you consider a feature where the author, subreddit, and the number of upvotes are seen also? As I can see, those data mentioned are available in the response of the API.

## Motivation
To have more Reddit feels to the shown meme image.

**Comment by version0chiro** [comment]
@rhanmiano yes that would definitely be feature! We use a reddit api clicking in the read.me, maybe you can get a start from there. Once you are done, submit a pull request and I will merge it to the code base! Welcome to open-source!

**Comment by rhanmiano** [comment]
@version0chiro Love it! Will update you, once I have wrapped it up.

**Comment by rhanmiano** [comment]
@version0chiro @devpnryn Hello, I've requested a pr about this feature. Hoping to get feedback from you. Thanks!

**Comment by version0chiro** [comment]
Yes @rhanmiano I have went over your PR and have merged to the main code base! Great work on the improvements!
